---
- name: gpg ~> configure github body params
  set_fact:
    github_body:
      armored_public_key: "{{ gpg_public_key }}"

- name: gpg ~> upload keys to github
  uri:
    method: POST
    url: "{{ github_rest_url }}"
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github.v3+json"
    body_format: json
    status_code: [201]
    body: "{{ github_body | to_json() }}"
  register: rs_github
  failed_when: rs_github.status != 201 and rs_github.status != 422 and rs_github.status != 304
  changed_when: rs_github.status == 201
