---
- include_tasks: preflight.yml

- name: gpg ~> check backup stat
  delegate_to: localhost
  stat:
    path: "{{ gpg_key_file }}"
  register: stat_gpg_key

- name: gpg ~> import key from file
  include_tasks: import.yml
  when: stat_gpg_key.stat.exists
