---
- name: gpg ~> update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == "Debian"

- name: gpg ~> set required packages for Debian
  set_fact:
    gpg_packages: gpg-agent
  when: ansible_os_family == "Debian"

- name: gpg ~> set required packages for RedHat
  set_fact:
    gpg_packages: gnupg
  when: ansible_os_family == "RedHat"

- name: gpg ~> ensure gpg agent installed
  package:
    name: "{{ gpg_packages }}"
    state: present

- name: gpg ~> ensure temp dir exists
  file:
    path: "{{ gpg_temp_dir }}"
    state: directory
    mode: "0777"
