---
- name: Converge
  hosts: all
  pre_tasks:
    - name: group ~> ensure group {{ gpg_group }} exists
      group:
        name: "{{ gpg_group }}"
        state: present
    - name: user ~> ensure user {{ gpg_user }} exists
      user:
        name: "{{ gpg_user }}"
        state: present
        group: "{{ gpg_group }}"
        create_home: true
  tasks:
    - name: "Include kilip.gpg"
      include_role:
        name: "kilip.gpg"
  vars:
    gpg_user: toni
    gpg_group: toni
    gpg_key_id: 1F41A0675D4C610F
    gpg_key_file: files/gpg/test1.key

    gpg_realname: Test Generate Key
    gpg_comment: Test Key
    gpg_email: foo@bar.com
